import './globals.css'
import type { Metadata } from 'next'
import Provider from '@/src/context/provider'
import { Rubik } from 'next/font/google'

const rubik = Rubik({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`bg-grayish ${rubik.className}`}>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  )
}
